---
- name: Copy systemd service file for NGINX
  template:
    src: simple-nginx.service.j2
    dest: /etc/systemd/system/simple-nginx.service
    owner: root
    group: root
    mode: '0644'
  notify:
    - Reload systemd
    - Restart nginx
