---
- name: Nginx Configuration | Create Supporting Directory Structure
  import_tasks: create_dirs.yml

- name: Synapse Configuration | Configure Nginx
  import_tasks: configure_nginx.yml

- name: Synapse Configuration | Create Well-known Configuration
  import_tasks: configure_well-known.yml

- name: Synapse Configuration | Create Systemd Service
  import_tasks: configure_systemd.yml

    #- name: Synapse Configuration | Create LetsEncrypt Job
    #  import_tasks: configure_ssl.yml

    #- name: Synapse Configuration | Create Cronjob for LetsEncrypt
    #  import_tasks: configure_certbot_cron.yml
