# tasks/main.yml
# Main task file that includes all sub-task files.

- name: Include pre-requisites tasks
  ansible.builtin.import_tasks: pre/main.yml

- name: Include Synapse Tasks
  ansible.builtin.import_tasks: synapse/main.yml

- name: Include NTFY Tasks
  ansible.builtin.import_tasks: ntfy/main.yml

- name: Include Element Web Tasks
  ansible.builtin.import_tasks: element/main.yml

- name: Include Nginx Tasks
  ansible.builtin.import_tasks: nginx/main.yml
