---
- name: Restart Synapse
  ansible.builtin.systemd:
    name: simple-synapse
    state: restarted

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Restart nginx
  ansible.builtin.systemd:
    name: simple-nginx
    state: restarted

- name: Restart simple-coturn
  ansible.builtin.systemd:
    name: simple-coturn
    state: restarted
