---
- name: Get UID of the synapse user
  command: id -u {{ synapse_user }}
  register: synapse_uid
  changed_when: false

- name: Get GID of the synapse user
  command: id -g {{ synapse_user }}
  register: synapse_gid
  changed_when: false

- name: Create systemd service file for Synapse
  ansible.builtin.template:
    src: simple-synapse.service.j2
    dest: /etc/systemd/system/simple-synapse.service
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload systemd
    - Restart Synapse

- name: Enable Synapse service to start on boot
  ansible.builtin.systemd:
    name: simple-synapse
    enabled: yes
