---
- name: Synapse Configuration | Add users
  import_tasks: add_user.yml

- name: Synapse Configuration | Create Supporting Directory Structure
  import_tasks: create_dirs.yml

- name: Synapse Configuration | Create Logging Support
  import_tasks: configure_logging.yml

- name: Synapse Configuration | Create Logging Support
  import_tasks: configure_logging.yml

- name: Synapse Configuration | Create Systemd Service
  import_tasks: configure_systemd.yml

- name: Synapse Configuration | Create homeserver.yaml
  import_tasks: configure_homeserver.yml
