---
- name: Copy .well-known configuration
  template:
    src: element.config.json.j2
    dest: /opt/element/config/config.json
    owner: "{{ synapse_user }}"
    group: "{{ synapse_user }}"
    mode: '0644'
